version: "3.5"
services:
  devcontainer:
    container_name: devcontainer
    image: ghcr.io/ifooth/devcontainer:main
    restart: always
    network_mode: host
    hostname: devcontainer
    env_file:
      - dev.env
    volumes:
      - /data/devcontainer/data:/data
      - /data/devcontainer/root:/root
      - /var/run/docker.sock:/var/run/docker.sock

  devcontainer-nightly:
    container_name: devcontainer-nightly
    image: ghcr.io/ifooth/devcontainer:latest
    restart: always
    network_mode: host
    hostname: devcontainer-nightly
    env_file:
      - dev.env
    environment:
      SSHD_PORT: 36023 # custom sshd port
      DEV_SERVER_PORT: 8023 # custom dev server port
      PRE_SCRIPT_FILE: /usr/local/bin/pre-script.sh
      POST_SCRIPT_FILE: /usr/local/bin/post-script.sh
    volumes:
      - /data/devcontainer-nightly/data:/data
      - /data/devcontainer-nightly/root:/root
      # - ./pre-script.sh:/usr/local/bin/pre-script.sh your custom pre script
      # - ./post-script.sh:/usr/local/bin/post-script.sh your custom post script
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=true
      - TZ=Asia/Shanghai
    command:
      - devcontainer-nightly
      - devcontainer

  redis:
    container_name: redis
    image: redis:6.0.10
    restart: always
    network_mode: host
    command: redis-server --appendonly yes
    volumes:
      - /data/redis:/data
    ports:
      - 6379:6379

  mariadb:
    container_name: mariadb
    image: mariadb:10.4.19
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
